Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :library_rooms

  get 'sessions/logout' => 'sessions#logout'
  post 'users/dum', to: 'users#dum', :as => 'dum'
  get 'users/dum', to: 'users#dum', :as => 'dumget'
  get 'users/admincreation', to: 'users#admincreation', :as => 'admins'
  get 'users/admdel', to: 'users#admdel', :as => 'admdel'
  get 'users/admview', to: 'users#admview', :as => 'admview'
  get 'users/memsview', to: 'users#memsview', :as => 'memsview'
  get 'users/libmems', to: 'users#libmems', :as => 'libmems'
  get 'booking_histories/index', to: 'booking_histories#index', :as => 'booking_histories'

  get 'users/libuser', to: 'users#libuser', :as => 'libuser'
  get 'users/addrooms', to: 'users#addrooms', :as => 'addrooms'
  #get 'booking_histories/viewhist', to: 'booking_histories#viewhist', :as => 'viewhist'
  get 'users/memsdel', to: 'users#memsdel', :as => 'memsdel'
  get '/users/index',to: 'users#index',as: 'users'
  post '/users/delete', to: 'users#destroy', as: 'del_user'
  post '/users/new',to: 'users#new',as: 'new_user'
  get '/users/edit',to: 'users#edit',as:'edit_user'
  get '/users/editprof',to: 'users#editprof',as:'editprof'
  get '/users/show', to: 'users#show', as: 'user'
  get '/users/admincreation', to: 'users#admincreation', as: 'admincreation'
  post '/users/adminupdate', to: 'users#adminupdate', as: 'adminupdate'
  get '/users/destroy',to: 'users#destroy'
  post '/users/update',to: 'users#update', as: 'update_user'
  post '/users/create',to: 'users#create', as: 'create_user'
  get '/users/new', to: 'users#new', as: 'get_user'

  post '/booking_histories/search',to: 'booking_histories#search',as: 'search_booking_history'
  get '/sessions/index', to: 'sessions#index', as: 'loggingout'
  get '/sessions/new', to: 'sessions#new', as: 'home'
  get '/booking_histories/new',to: 'booking_histories#new',as: 'new_booking_history'
  get '/booking_histories/edit',to: 'booking_histories#edit',as:'edit_booking_history'
  get '/booking_histories/show', to: 'booking_histories#show', as: 'booking_history'
  post '/booking_histories/destroy',to: 'booking_histories#destroy' ,as: 'destroy_booking_history'
  post '/booking_histories/create',to: 'booking_histories#create'
  get '/booking_histories/bookingdel', to: 'booking_histories#bookingdel' ,as: 'bookingdel_booking_history'
  get '/booking_histories/bkhist', to: 'booking_histories#bkhist' ,as: 'bkhist_booking_history'
  post '/booking_histories/memshist', to: 'booking_histories#memshist' ,as: 'memshist'
  get '/booking_histories/modify', to: 'booking_histories#modify' ,as: 'modify'

  get '/notifs/addteam', to: 'notifs#addteam' ,as: 'addteam'
  post '/notifs/newteam', to: 'notifs#newteam' ,as: 'newteam'
  post '/notifs/create', to: 'notifs#create' ,as: 'create_notif'
  get '/notifs/update', to: 'notifs#update' ,as: 'update_notif'
  get '/notifs/index', to: 'notifs#index' ,as: 'index_notif'
  get '/notifs/edit', to: 'notifs#edit' ,as: 'edit_notif'
  get '/notifs/new', to: 'notifs#new' ,as: 'new_notif'
  get '/notifs/destroy', to: 'notifs#destroy' ,as: 'destroy_notif'
  get '/notifs/show', to: 'notifs#show' ,as: 'show_notif'


  root 'sessions#new'
end
